FEDERATION_SERVER="https://api.stellar.org/federation"

ACCOUNTS=["",
""
]

[DOCUMENTATION]
ORG_NAME="GOPE STOCK MARKET" 
ORG_URL="https://gope.top" 
ORG_LOGO="https://gope.top/logo/gope.png" 

[[CURRENCIES]]
code="RUPIAH" 
issuer="" 
status="live" 
name="RUPIAH" 
desc="RUPIAH is base currency in GOPE STOCK MARKET. Please visit https://gope.top for more details." 
display_decimals=0 
image="https://gope.top/logo/rupiah.png" 
conditions="If you want to follow Initial Public Offering (IPO) of Indonesian stocks (in Indonesia Stock Exchange) via Stellar Blockchain, then buy this token as base currency to enter and exit from GOPE STOCKS MARKET." 
is_asset_anchored="true" 
anchor_asset_type="fiat" 
anchor_asset="RUPIAH" 
redemption_instructions="Wait until IPO running at least 7 working days (please see the schedules). If you see RUPIAH or XLM in BUY positions already standby (inside SDEX), it means you ready to withdraw your stocks become cash. We also guide you the routes to withdraw and convert your tokens become real money." 

[[CURRENCIES]]
code="SWID" 
issuer="" 
status="live" 
name="Stock of SWID" 
desc="1 SWID Token in GOPE STOCK MARKET is equivalent with 1 Lot of SWID Stock in Indonesia Stock Exchange." 
display_decimals=0 
image="https://gope.top/logo/swid.png" 
conditions="If you want to follow Initial Public Offering (IPO) of Indonesian stocks via Stellar blockchain, then buy this token to generate profits for your own." 
is_asset_anchored="true" 
anchor_asset_type="stock" 
anchor_asset="SWID" 
redemption_instructions="Wait until IPO running at least 7 working days (please see the schedules). If you see RUPIAH or XLM in BUY positions already standby (inside SDEX), it means you ready to withdraw your stocks become cash. We also guide you the routes to withdraw and convert your tokens become real money." 
fixed_number=3400000 

[[CURRENCIES]]
code="TRGU" 
issuer="" 
status="live" 
name="Stock of TRGU" 

display_decimals=0 
image="https://gope.top/logo/trgu.png" 
conditions="If you want to follow Initial Public Offering (IPO) of Indonesian stocks via Stellar blockchain, then buy this token to generate profits for your own." 
is_asset_anchored="true" 
anchor_asset_type="stock" 
anchor_asset="TRGU" 
redemption_instructions="Wait until IPO running at least 7 working days (please see the schedules). If you see RUPIAH or XLM in BUY positions already standby (inside SDEX), it means you ready to withdraw your stocks become cash. We also guide you the routes to withdraw and convert your tokens become real money." 
fixed_number=15000000 

[[CURRENCIES]]
code="ARKO" 
issuer="" 
status="live" 
name="Stock of ARKO" 

display_decimals=0 
image="https://gope.top/logo/arko.png" 
conditions="If you want to follow Initial Public Offering (IPO) of Indonesian stocks via Stellar blockchain, then buy this token to generate profits for your own." 
is_asset_anchored="true" 
anchor_asset_type="stock" 
anchor_asset="ARKO" 
redemption_instructions="Wait until IPO running at least 7 working days (please see the schedules). If you see RUPIAH or XLM in BUY positions already standby (inside SDEX), it means you ready to withdraw your stocks become cash. We also guide you the routes to withdraw and convert your tokens become real money." 
fixed_number=5799000 

[[CURRENCIES]]
code="CHEM" 
issuer="" 
status="live" 
name="Stock of CHEM" 

display_decimals=0 
image="https://gope.top/logo/chem.png" 
conditions="If you want to follow Initial Public Offering (IPO) of Indonesian stocks via Stellar blockchain, then buy this token to generate profits for your own." 
is_asset_anchored="true" 
anchor_asset_type="stock" 
anchor_asset="CHEM" 
redemption_instructions="Wait until IPO running at least 7 working days (please see the schedules). If you see RUPIAH or XLM in BUY positions already standby (inside SDEX), it means you ready to withdraw your stocks become cash. We also guide you the routes to withdraw and convert your tokens become real money." 
fixed_number=5000000 

[[CURRENCIES]]
code="DEWI" 
issuer="" 
status="live" 
name="Stock of DEWI" 

display_decimals=0 
image="https://gope.top/logo/dewi.png" 
conditions="If you want to follow Initial Public Offering (IPO) of Indonesian stocks via Stellar blockchain, then buy this token to generate profits for your own." 
is_asset_anchored="true" 
anchor_asset_type="stock" 
anchor_asset="DEWI" 
redemption_instructions="Wait until IPO running at least 7 working days (please see the schedules). If you see RUPIAH or XLM in BUY positions already standby (inside SDEX), it means you ready to withdraw your stocks become cash. We also guide you the routes to withdraw and convert your tokens become real money." 
fixed_number=7000000 

[[CURRENCIES]]
code="AXIO" 
issuer="" 
status="live" 
name="Stock of AXIO" 

display_decimals=0 
image="https://gope.top/logo/axio.png" 
conditions="If you want to follow Initial Public Offering (IPO) of Indonesian stocks via Stellar blockchain, then buy this token to generate profits for your own." 
is_asset_anchored="true" 
anchor_asset_type="stock" 
anchor_asset="AXIO" 
redemption_instructions="Wait until IPO running at least 7 working days (please see the schedules). If you see RUPIAH or XLM in BUY positions already standby (inside SDEX), it means you ready to withdraw your stocks become cash. We also guide you the routes to withdraw and convert your tokens become real money." 
fixed_number=10401265 

[[CURRENCIES]]
code="HILL" 
issuer="" 
status="live" 
name="Stock of HILL" 

display_decimals=0 
image="https://gope.top/logo/hill.png" 
conditions="If you want to follow Initial Public Offering (IPO) of Indonesian stocks via Stellar blockchain, then buy this token to generate profits for your own." 
is_asset_anchored="true" 
anchor_asset_type="stock" 
anchor_asset="HILL" 
redemption_instructions="Wait until IPO running at least 7 working days (please see the schedules). If you see RUPIAH or XLM in BUY positions already standby (inside SDEX), it means you ready to withdraw your stocks become cash. We also guide you the routes to withdraw and convert your tokens become real money." 
fixed_number=22115000 

[[CURRENCIES]]
code="HATM" 
issuer="" 
status="live" 
name="Stock of HATM" 

display_decimals=0 
image="https://gope.top/logo/hatm.png" 
conditions="If you want to follow Initial Public Offering (IPO) of Indonesian stocks via Stellar blockchain, then buy this token to generate profits for your own." 
is_asset_anchored="true" 
anchor_asset_type="stock" 
anchor_asset="HATM" 
redemption_instructions="Wait until IPO running at least 7 working days (please see the schedules). If you see RUPIAH or XLM in BUY positions already standby (inside SDEX), it means you ready to withdraw your stocks become cash. We also guide you the routes to withdraw and convert your tokens become real money." 
fixed_number=12200000 

[[CURRENCIES]]
code="KRYA" 
issuer="" 
status="live" 
name="Stock of KRYA" 

display_decimals=0 
image="https://gope.top/logo/krya.png" 
conditions="If you want to follow Initial Public Offering (IPO) of Indonesian stocks via Stellar blockchain, then buy this token to generate profits for your own." 
is_asset_anchored="true" 
anchor_asset_type="stock" 
anchor_asset="KRYA" 
redemption_instructions="Wait until IPO running at least 7 working days (please see the schedules). If you see RUPIAH or XLM in BUY positions already standby (inside SDEX), it means you ready to withdraw your stocks become cash. We also guide you the routes to withdraw and convert your tokens become real money." 
fixed_number=3250000 

[[CURRENCIES]]
code="GULA" 
issuer="" 
status="live" 
name="Stock of GULA" 

display_decimals=0 
image="https://gope.top/logo/gula.png" 
conditions="If you want to follow Initial Public Offering (IPO) of Indonesian stocks via Stellar blockchain, then buy this token to generate profits for your own." 
is_asset_anchored="true" 
anchor_asset_type="stock" 
anchor_asset="GULA" 
redemption_instructions="Wait until IPO running at least 7 working days (please see the schedules). If you see RUPIAH or XLM in BUY positions already standby (inside SDEX), it means you ready to withdraw your stocks become cash. We also guide you the routes to withdraw and convert your tokens become real money."
fixed_number=2140725 






